<a href="https://colab.research.google.com/github/zaw-1808/Singapore-suicide-mortality-analysis-Mini-project-/blob/main/singapore_suicide_mortality(2015_2024).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
from google.colab import files

uploaded = files.upload()

Saving MIni project SG.xlsx to MIni project SG (2).xlsx

In [24]:
import pandas as pd

df = pd.read_excel('MIni project SG.xlsx')


df.head()

,Unnamed: 0,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Males,11.4,11.0,10.2,12.1,11.0,12.6,10.5,11.9,11.2,7.6
1,Females,5.6,6.2,5.4,4.8,5.2,5.3,5.1,6.4,5.4,4.3
2,34 Years And Below,5.1,4.2,3.5,5.4,5.1,4.9,6.1,6.1,6.4,4.8
3,35 - 64 Years,9.3,10.5,8.2,8.9,9.0,9.5,7.3,9.1,7.9,5.7
4,65 Years And Above,17.4,16.2,19.7,15.5,13.2,17.7,13.1,16.4,13.1,8.9

In [25]:
df = df.rename(columns={'Unnamed: 0': 'Subcategory'})
df

,Subcategory,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Males,11.4,11.0,10.2,12.1,11.0,12.6,10.5,11.9,11.2,7.6
1,Females,5.6,6.2,5.4,4.8,5.2,5.3,5.1,6.4,5.4,4.3
2,34 Years And Below,5.1,4.2,3.5,5.4,5.1,4.9,6.1,6.1,6.4,4.8
3,35 - 64 Years,9.3,10.5,8.2,8.9,9.0,9.5,7.3,9.1,7.9,5.7
4,65 Years And Above,17.4,16.2,19.7,15.5,13.2,17.7,13.1,16.4,13.1,8.9

In [26]:
!pip install plotly

Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (5.24.1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly) (26.0)

In [27]:
import pandas as pd
import plotly.express as px
df_long['Year'] = df_long['Year'].astype(int)

In [28]:
fig = px.line(
    df_long,
    x='Year',
    y='Rate',
    color='Subcategory',        # separate line for each subgroup
    title='Suicide Mortality Rate (2015-2024)',
    hover_data=['MainCategory'],
    labels={'Rate':'Rate per 100,000'}
)

# Add interactive filter (dropdown slicer) for MainCategory
fig.update_layout(
    updatemenus=[
        dict(
            buttons=list([
                dict(label="All",
                     method="update",
                     args=[{"visible": [True]*len(df_long['Subcategory'].unique())}]),
                dict(label="Age",
                     method="update",
                     args=[{"visible": [sub in df_long[df_long['MainCategory']=='Age']['Subcategory'].unique() for sub in df_long['Subcategory'].unique()]}]),
                dict(label="Sex",
                     method="update",
                     args=[{"visible": [sub in df_long[df_long['MainCategory']=='Sex']['Subcategory'].unique() for sub in df_long['Subcategory'].unique()]}])
            ]),
            direction="down",
        )
    ]
)

fig.show()

In [29]:
# 1️⃣ Install Plotly (if not already installed)
!pip install plotly

# 2️⃣ Import libraries
import pandas as pd
import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go

# 3️⃣ Prepare your data
data = {
    'Subcategory': [
        'Males','Males','Males','Males','Males','Males','Males','Males','Males','Males',
        'Females','Females','Females','Females','Females','Females','Females','Females','Females','Females',
        '34 Years And Below','34 Years And Below','34 Years And Below','34 Years And Below','34 Years And Below',
        '34 Years And Below','34 Years And Below','34 Years And Below','34 Years And Below','34 Years And Below',
        '35 - 64 Years','35 - 64 Years','35 - 64 Years','35 - 64 Years','35 - 64 Years','35 - 64 Years','35 - 64 Years','35 - 64 Years','35 - 64 Years','35 - 64 Years',
        '65 Years And Above','65 Years And Above','65 Years And Above','65 Years And Above','65 Years And Above','65 Years And Above','65 Years And Above','65 Years And Above','65 Years And Above','65 Years And Above'
    ],
    'Year': [2015,2016,2017,2018,2019,2020,2021,2022,2023,2024]*5,
    'Rate': [
        11.4,11.0,10.2,12.1,11.0,12.6,10.5,11.9,11.2,7.6,
        5.6,6.2,5.4,4.8,5.2,5.3,5.1,6.4,5.4,4.3,
        5.1,4.2,3.5,5.4,5.1,4.9,6.1,6.1,6.4,4.8,
        9.3,10.5,8.2,8.9,9.0,9.5,7.3,9.1,7.9,5.7,
        17.4,16.2,19.7,15.5,13.2,17.7,13.1,16.4,13.1,8.9
    ]
}

df_long = pd.DataFrame(data)

# 4️⃣ Add MainCategory
def main_category(sub):
    if sub in ['Males','Females']:
        return 'Sex'
    else:
        return 'Age'

df_long['MainCategory'] = df_long['Subcategory'].apply(main_category)
df_long['Year'] = df_long['Year'].astype(int)

# 5️⃣ Separate data for Age and Sex charts
age_df = df_long[df_long['MainCategory']=='Age']
sex_df = df_long[df_long['MainCategory']=='Sex']

# 6️⃣ Create subplots (2 charts side by side)
fig = make_subplots(rows=1, cols=2, subplot_titles=("Age Groups", "Sex Groups"))

# Add Age group lines
for sub in age_df['Subcategory'].unique():
    sub_df = age_df[age_df['Subcategory']==sub]
    fig.add_trace(go.Scatter(x=sub_df['Year'], y=sub_df['Rate'], mode='lines+markers', name=sub), row=1, col=1)

# Add Sex group lines
for sub in sex_df['Subcategory'].unique():
    sub_df = sex_df[sex_df['Subcategory']==sub]
    fig.add_trace(go.Scatter(x=sub_df['Year'], y=sub_df['Rate'], mode='lines+markers', name=sub), row=1, col=2)

# 7️⃣ Update layout
fig.update_layout(
    title_text="Suicide Mortality Rate Dashboard (2015-2024)",
    xaxis_title="Year",
    yaxis_title="Rate per 100,000",
    legend_title="Subcategory",
    width=1000,
    height=500
)

fig.show()

Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (5.24.1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly) (26.0)